LinkShortener/Entities/Exceptions/ErrorDetails.cs
namespace LinkShortener.Entities.Exceptions;

public class ErrorDetails
{
    public int StatusCode { get; set; }
    public string? Message { get; set; }

    public override string ToString() => $"<h1>Error {StatusCode}: {Message}</h1>";
}

LinkShortener/Entities/Exceptions/ErrorViewModel.cs
namespace LinkShortener.Entities.Exceptions;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

LinkShortener/Entities/Exceptions/LinkNotFoundException.cs
namespace LinkShortener.Entities.Exceptions;

public class LinkNotFoundException : NotFoundException
{
    public LinkNotFoundException()
        : base("The link with this URL was not found.")
    { }
}

LinkShortener/Entities/Exceptions/NotFoundException.cs
namespace LinkShortener.Entities.Exceptions;

public abstract class NotFoundException : Exception
{
    protected NotFoundException(string message)
        : base(message)
    { }
}

LinkShortener/Entities/Link.cs
using System.ComponentModel.DataAnnotations;
namespace LinkShortener.Entities;

public class Link
{
    public Guid Id { get; set; }

    [Required(ErrorMessage = "UrlLong is a required field.")]
    public string? UrlLong { get; set; }

    [Required(ErrorMessage = "UrlShort is a required field.")]
    public string? UrlShort { get; set; }

    public DateTime CreationDate { get; set; }

    public int NumberOfClicks { get; set; }
}

LinkShortener/Controllers/LinkController.cs
using LinkShortener.Service.Contracts;
using LinkShortener.Shared.DataTransferObjects;
using Microsoft.AspNetCore.Mvc;
namespace LinkShortener.Controllers;

public class LinkController : Controller
{
    private readonly IServiceManager _service;
    public LinkController(IServiceManager service) => _service = service;


    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var links = await _service.LinkService.GetAllLinksAsync();
        return View(links);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(LinkDto link)
    {
        if (!Uri.IsWellFormedUriString(link.UrlLong, UriKind.Absolute))
            ModelState.AddModelError("UrlLong", "Please, enter correct URL.");

        if (ModelState.IsValid)
        {
            await _service.LinkService.CreateLinkAsync(link);
            return RedirectToAction("Index");
        }
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> Edit(Guid id)
    {
        var link = await _service.LinkService.GetLinkAsync(id);
        if (link is null)
            return NotFound();
        return View(link);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(Guid id, LinkDto link)
    {
        if (!Uri.IsWellFormedUriString(link.UrlLong, UriKind.Absolute))
            ModelState.AddModelError("UrlLong", "Please, enter correct URL.");

        if (ModelState.IsValid)
        {
            await _service.LinkService.UpdateLinkAsync(id, link);
            return RedirectToAction("Index");
        }
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Delete(Guid id)
    {
        await _service.LinkService.DeleteLinkAsync(id);
        return RedirectToAction("Index");
    }

    [HttpGet("{urlShort}")]
    public async Task<IActionResult> RedirectToLongUrl(string urlShort)
    {
        var link = await _service.LinkService.GetLinkByUrlShortAsync(urlShort);

        if (link is null)
            return NotFound();

        link.NumberOfClicks++;
        await _service.LinkService.UpdateLinkAsync(link.Id, link);

        return Redirect(link.UrlLong!);
    }
}

LinkShortener/Views/Link/Create.cshtml
@model LinkDto
@{
    ViewData["Title"] = "Create link";
}

<div class="d-flex align-items-center justify-content-center pt-md-5" >
    <form method="post">
        <div class="p-4 mt-4 border border-light" style="width: 500px">

            <div class="row pb-2">
                <h2 class="text-primary text-center">Add link</h2>
            </div>

            <div class="mb-3">
                <label asp-for="UrlLong">Your URL</label>
                <input asp-for="UrlLong" class="form-control" />
                <span asp-validation-for="UrlLong" class="text-danger"></span>
            </div>

            <div class="d-flex justify-content-around">
                <button asp-controller="Link" asp-action="Create" type="submit" class="btn btn-primary p-2" style="width: 160px">
                    Add
                </button>
                <a asp-controller="Link" asp-action="Index" class="btn btn-secondary p-2" style="width: 160px">
                    Back to list
                </a>
            </div>
        </div>
    </form>
</div>


@section Scripts 
{
    <partial name="_ValidationScriptsPartial" />
}

LinkShortener/Views/Link/Edit.cshtml
@model LinkDto
@{
    ViewData["Title"] = "Edit link";
}

<div class="d-flex align-items-center justify-content-center pt-md-5" >
    <form method="post">
        <div class="p-4 mt-4 border border-light" style="width: 500px">

            <div class="row pb-2">
                <h2 class="text-primary text-center">Edit link</h2>
            </div>

            <div class="mb-3">
                <label asp-for="UrlLong">Your URL</label>
                <input asp-for="UrlLong" class="form-control" />
                <span asp-validation-for="UrlLong" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="CreationDate">Created at</label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="UrlShort">Short URL</label>
                <input asp-for="UrlShort" class="form-control" disabled/>
                <span asp-validation-for="UrlShort" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="NumberOfClicks">Number of Clicks</label>
                <input asp-for="NumberOfClicks" class="form-control" disabled/>
                <span asp-validation-for="NumberOfClicks" class="text-danger"></span>
            </div>

            <div class="d-flex justify-content-around">
                <button asp-controller="Link" asp-action="Edit" type="submit"
                        class="btn btn-primary p-2" style="width: 160px">
                    Update
                </button>
                <a asp-controller="Link" asp-action="Index" class="btn btn-secondary p-2" style="width: 160px">Back to list</a>
            </div>
        </div>
    </form>
</div>


@section Scripts 
{
    <partial name="_ValidationScriptsPartial" />
}

LinkShortener/Views/Link/Index.cshtml
@model IEnumerable<LinkDto>
@{
    ViewData["Title"] = "Links Page";
}

<div class="text-center">
    <h1 class="display-4">Link Shortener</h1>

    <div class="row pt-4">
        <div class="col-6"></div>
        <div class="col-6 text-end">
            <a asp-controller="Link" asp-action="Create" class="btn btn-primary p-2" style="width: 200px">
                <i class="bi bi-plus-circle"></i>
                &nbsp; Add new link
            </a>
        </div>
    </div>
    <br />

    <table class="table" style="width:100%">
        <thead class="bg-dark">
            <tr>
                <th>Long URL</th>
                <th>Short URL</th>
                <th>Creation Date</th>
                <th>Clicks</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var link in Model)
            {
                <tr>
                    <td width="20%"><a href=@link.UrlLong>@link.UrlLong</a></td>
                    <td width="10%"><a href=@link.UrlShort>@link.UrlShort</a></td>
                    <td width="10%">@link.CreationDate</td>
                    <td width="8%">@link.NumberOfClicks</td>
                    <td width="10%">
                        <div class="btn-group w-75" role="group">
                            <a asp-controller="Link" asp-action="Edit" asp-route-id="@link.Id"
                               class="btn btn-info mx-1">
                                <i class="bi bi-pencil-square"></i>
                                &nbsp; Edit
                            </a>
                        </div>
                    </td>
                    <td width="10%">
                        <div class="btn-group w-75" role="group">
                            <form method="post" asp-controller="Link" asp-action="Delete" asp-route-id="@link.Id">
                                <button class="btn btn-danger mx-1" type="submit" style="width: 100px">
                                    <i class="bi bi-trash3"></i>
                                    &nbsp; Delete
                                </button>
                            </form>
                        </div>
                    </td>
                </tr>
            }
    </table>
</div>

LinkShortener/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LinkShortener</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LinkShortener.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-gradient">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Link" asp-action="Index">LinkShortener</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Link" asp-action="Index">Links</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LinkShortener - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>